"""
This file is generated by Claude Code and reviewed by us, it is used to test the
hardware implementation, as described below.

fft_ref.py -- bit-accurate fixed-point golden model of the SeeTheBeat FFT.

This is the *reference* the RTL will be tested against. It implements EXACTLY the
numeric spec agreed in Step 1.2 (see SeeTheBeat_LearningNotes.pdf / CLAUDE.md):

    Samples/datapath : 16-bit signed, Q1.15, range [-1, +1)
    Complex value    : { real Q1.15, imag Q1.15 }
    Algorithm        : radix-2 decimation-in-time (DIT), in-place, bit-reversed input
    Scaling          : unconditional >>1 after each stage  (scaled FFT, out = X/N)
    Rounding         : TRUNCATION (arithmetic shift right, i.e. floor toward -inf)
    Twiddles         : ideal cos/sin quantized to Q1.15  (a stand-in for the CORDIC
                       rotation; Phase 2 replaces this multiply with the CORDIC model)

Pure standard library on purpose -- no numpy -- so it runs identically on the Windows
host and in the devcontainer. Values are kept as plain Python ints; Python's `>>` on a
negative int is an arithmetic (floor) shift, which is exactly the hardware truncation
we specified.

Why no overflow: with real input |x[n]| <= 1.0 (i.e. |x| <= 32767), the scaled FFT keeps
every complex *magnitude* <= 1.0 through all stages (a stage at most doubles magnitude,
then >>1 halves it), so each 16-bit real/imag component stays in range. The one edge is
the sample value -32768 (magnitude 32768, just over 1.0); test vectors avoid it.
"""

import math

Q = 15                      # fractional bits (Q1.15)
ONE = 1 << Q                # 32768 == "1.0"
INT16_MIN = -(1 << 15)      # -32768
INT16_MAX = (1 << 15) - 1   #  32767

# ---- cached per-N tables (twiddles + bit-reversal) --------------------------
_TW_CACHE = {}
_BR_CACHE = {}


def _q15(x):
    """Quantize a real number in [-1,1) to a Q1.15 int (round-to-nearest, clamped)."""
    v = int(math.floor(x * ONE + 0.5))
    return max(INT16_MIN, min(INT16_MAX, v))


def twiddles(N):
    """Twiddle table W_N^k = cos(2*pi*k/N) - j*sin(2*pi*k/N), k = 0..N/2-1, as Q1.15.

    Returns (tw_re, tw_im). Rounded to nearest (this is a constant table, unaffected by
    the per-stage truncation decision).
    """
    if N not in _TW_CACHE:
        half = N // 2
        tw_re = [0] * half
        tw_im = [0] * half
        for k in range(half):
            ang = 2.0 * math.pi * k / N
            tw_re[k] = _q15(math.cos(ang))     # cos(2*pi*k/N)
            tw_im[k] = _q15(-math.sin(ang))    # -sin(2*pi*k/N)  (W = cos - j sin)
        _TW_CACHE[N] = (tw_re, tw_im)
    return _TW_CACHE[N]


def bitrev_table(N):
    """Permutation that maps position i -> bit-reversed index (over log2(N) bits)."""
    if N not in _BR_CACHE:
        bits = N.bit_length() - 1
        assert (1 << bits) == N, "N must be a power of two"
        _BR_CACHE[N] = [int(format(i, "0{}b".format(bits))[::-1], 2) for i in range(N)]
    return _BR_CACHE[N]


def fft_fixed(x_re, x_im=None, N=None):
    """Fixed-point radix-2 DIT FFT (the golden model).

    Args:
        x_re: list of N ints (Q1.15) -- the real input samples.
        x_im: list of N ints (Q1.15) or None (treated as all-zero, i.e. real input).
        N   : transform size (defaults to len(x_re)); must be a power of two.

    Returns:
        (re, im): two lists of N ints (Q1.15) holding X[k]/N in natural bin order.
    """
    if N is None:
        N = len(x_re)
    assert len(x_re) == N, "x_re length must equal N"
    tw_re, tw_im = twiddles(N)
    br = bitrev_table(N)

    # Load inputs in bit-reversed order (DIT with natural-order output).
    re = [x_re[br[i]] for i in range(N)]
    im = [0] * N if x_im is None else [x_im[br[i]] for i in range(N)]

    bits = N.bit_length() - 1
    for s in range(1, bits + 1):          # stage 1 .. log2(N)
        m = 1 << s                        # group size (2,4,8,...)
        half = m >> 1                     # butterfly span / stride within the group
        tstep = N // m                    # twiddle index step: k = j * tstep
        for kstart in range(0, N, m):
            for j in range(half):
                k = j * tstep
                wr, wi = tw_re[k], tw_im[k]
                i0 = kstart + j            # A
                i1 = i0 + half             # B
                ar, ai = re[i0], im[i0]
                br_, bi_ = re[i1], im[i1]

                # W * B, reduced from Q2.30 back to Q1.15 by an arithmetic (truncating)
                # shift. This multiply stands in for the CORDIC rotation (Phase 2).
                t_re = (wr * br_ - wi * bi_) >> Q
                t_im = (wr * bi_ + wi * br_) >> Q

                # Butterfly A +/- W*B, then the per-stage scale >>1 (TRUNCATION).
                re[i0] = (ar + t_re) >> 1
                im[i0] = (ai + t_im) >> 1
                re[i1] = (ar - t_re) >> 1
                im[i1] = (ai - t_im) >> 1

        # Dev-time guard: the scaled FFT must never overflow int16 for valid input.
        # If this ever fires, the scaling/gain assumptions are wrong -- do NOT silence.
        _assert_in_range(re, im)
    return re, im


def _assert_in_range(re, im):
    for v in re:
        assert INT16_MIN <= v <= INT16_MAX, "real overflow: {}".format(v)
    for v in im:
        assert INT16_MIN <= v <= INT16_MAX, "imag overflow: {}".format(v)


# ---- helpers used by tests --------------------------------------------------
def to_float(vals):
    """Q1.15 ints -> Python floats."""
    return [v / ONE for v in vals]


def fft_float(x):
    """Exact (floating-point) radix-2 FFT reference. x: list of complex/float."""
    N = len(x)
    if N == 1:
        return [complex(x[0])]
    even = fft_float(x[0::2])
    odd = fft_float(x[1::2])
    out = [0j] * N
    for k in range(N // 2):
        t = complex(math.cos(-2 * math.pi * k / N), math.sin(-2 * math.pi * k / N)) * odd[k]
        out[k] = even[k] + t
        out[k + N // 2] = even[k] - t
    return out
